version: '2'
services:

  #RabbitMQ broker, for Celery
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.7.3
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  #Flower UI for Celery queue
  ui:
    build: ./celery-ib
    command: flower -A worker --port=5555 --broker=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbit
    environment:
      - BROKER=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbit
    volumes:
      - ./worker:/worker
      - ./ibapi:/ibapi
    ports:
        - "127.0.0.1:5010:5555"
    links:
        - rabbit
    depends_on:
        - rabbit

  #Python Celery worker
  worker-1:
    build: ./celery-ib
    command: celery -A worker worker --loglevel=info -Ofair --concurrency=1
    environment:
      - BROKER=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbit
      - ECHEANCE_CAC40=${ECHEANCE_CAC40}
      - ECHEANCE_DAX=${ECHEANCE_DAX}
      - ECHEANCE_EUROSTOXX=${ECHEANCE_EUROSTOXX}
      - ECHEANCE_FTSEMIB=${ECHEANCE_FTSEMIB}
    volumes:
      - ./worker:/worker
      - ./ibapi:/ibapi
      - ./logs:/logs
    links:
      - tws:tws

  #Celery beat, to schedule periodic tasks
  beat:
    build: ./celery-ib
    command: celery -A worker beat --loglevel=info
    environment:
      - BROKER=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbit
    links:
        - rabbit
    depends_on:
        - postgres
        - rabbit
    volumes:
      - ./worker:/worker
      - ./ibapi:/ibapi

  #Interactive Broker containerized API
  tws:
    build: ./ib-docker
    ports:
      - "4003:4003"
      - "5901:5900"
    volumes:
      - ./ib-docker/ib/IBController.ini:/root/IBController/IBController.ini
      - ./ib-docker/ib/jts.ini:/root/Jts/jts.ini
    environment:
      - TZ=America/Chicago
      # Variables pulled from /IBController/IBControllerGatewayStart.sh
      - VNC_PASSWORD=password # CHANGEME
      - TWS_MAJOR_VRSN=974
      - IBC_INI=/root/IBController/IBController.ini
      - IBC_PATH=/opt/IBController
      - TWS_PATH=/root/Jts
      - TWS_CONFIG_PATH=/root/Jts
      - LOG_PATH=/opt/IBController/Logs
      - JAVA_PATH=/opt/i4j_jres/1.8.0_152/bin # JRE is bundled starting with TWS 952 
      - TRADING_MODE=paper # either paper or live
      - TWSUSERID=${TWS_USER} # IB account
      - TWSPASSWORD=${TWS_PASSWORD} # IB account password
      - FIXUSERID=
      - FIXPASSWORD=
      - APP=GATEWAY

  #Database
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db:/init

  #Database web client
  pgweb:
    image: sosedoff/pgweb
    command: pgweb --readonly --bind=0.0.0.0 --listen=8081
    ports: ["127.0.0.1:8080:8081"]
    links:
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DATABASE}?sslmode=disable
    depends_on:
      - postgres

  #Grafana to explore and visualise data
  grafana:
    image: grafana/grafana:5.0.3
    restart: always
    ports:
        - "127.0.0.1:7000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
